### ISSUE TITLE
Open Question: dealing with failed RimWorld patches

### ISSUE THREAD

**Issue by Vectorial1024** [UnlimitedHugs/RimworldHugsLib#110]
I don't know where else to put this; feel free to link this to elsewhere which may be more suitable.

The problem is this: in RimWorld 1.5, `Verse.Log::Error` no longer forces the appearance of the debug log when dev-mode is off, which makes a lot of errors "invisible". At least this is the observation on my side.

This reduces our general awareness of bugs, which can be a problem. For example, failed patches that generate a red error is now invisible when dev-mode is off, which means regular users simply do not notice any errors until they somehow remember to open the debug log and look at what is going on.

**Comment by Vectorial1024** [comment]
I have made another mod Visible Error Logs https://steamcommunity.com/sharedfiles/filedetails/?id=3248417388 ; perhaps this is useful.

**Comment by UnlimitedHugs** [comment]
This has been a valid point of contention in Rimworld modding pretty much since the beginning.
A dedicated mod is a good solution, because it gives the choice to the player. There is also value in hiding errors and traces from non-technical folks to avoid disrupting their experience. This is somewhat passable due to the non-fatal nature of most mod errors.
