### ISSUE TITLE
Adding mod load order resolver

### ISSUE THREAD

**Issue by PhOder** [UnlimitedHugs/RimworldHugsLib#40]
I just thought it'd be possible for people to add information in ways of "load me after/before <mod x>". This would result in a dependency graph that could lead to an automatic resolvement for mod load order and hint the player for cyclic dependency problems.

Eventually this could even be solved by finding out what game elements each mod touches and make a dependency resolution graph from this. But implementing this would probably take a while.

If you like the idea but don't have the time to add a feature such as this I'd be willing to take a look at your code and maybe implement something like that myself.

**Comment by UnlimitedHugs** [comment]
While a neat feature, and something my own mods would benefit of, HugsLib might not be the best place to house it. The reason is that if HugsLib is not loaded or the load order is off, you would still want the rules enforced, and helpful messages to be displayed.

For my own mods, I include the [HugsLibChecker](https://github.com/UnlimitedHugs/RimworldHugsLibChecker) assembly that verifies load order and version requirements. If you'd like a beefier and more versatile version of that, you could check out @scuba156 [Dependency checker](https://ludeon.com/forums/index.php?topic=34379.0). The project is not finished/up to date, but it could be a good starting point for further work.

**Comment by scuba156** [comment]
I've updated the repo for [Dependency Checker](https://github.com/scuba156/DependencyChecker) and its counterpart [Dependency File Creator](https://github.com/scuba156/DependencyFileCreator). I'm not sure of the current state they are in. 

I may continue it in the future, but your free to use it as you like.

**Comment by PhOder** [comment]
Almost thought that this wouldn't quite fit in HugsLib. I'll go and check @scuba156 's out. Thanks for hinting me there :+1:
