### ISSUE TITLE
Languages appear twice in the language selector

### ISSUE THREAD

**Issue by Hechicera64** [UnlimitedHugs/RimworldHugsLib#66]
On release candidate on unstable 1.1.2607

Heave Harmony, Core, Royalty, Hugslib only listed in mods. Restart. Open options, Open Select Language. Here is a clip of the Spanish options (in Spanish). There are only two, but you see four.

https://cdn.discordapp.com/attachments/684960023020961815/700853683029671956/Spanish.PNG

May effect other in game lists. It works, but is confusing to read.

**Comment by UnlimitedHugs** [comment]
It's a vanilla issue that only becomes apparent when mods with translations are loaded.

Short answer: when changing languages, want to select `German (Deutsch)`, not `German`.

Long answer: what happens is that, due to an oversight, language folders are loaded twice. In one of those cases it takes into account the legacy name ("German"), and in the other it doesn't- and the loaded language is added as a separate entry.
As a result, `German (Deutsch)` will contain both vanilla and modded translation strings, while `German` will only contain the modded ones.

**Comment by Hechicera64** [comment]
Thanks for looking at it, bounced the info back over to the unstable test discord.
