### ISSUE TITLE
Upload error: Unknown Error

### ISSUE THREAD

**Issue by tukoz** [UnlimitedHugs/RimworldHugsLib#76]
While it has worked before (e.g. 2020-02) I cannot get HugsLib to publish any sort of logs this year (first tried in February). Pops up the following error:

    Upload error: Unknown Error

I symlinked the log /tmp/rimworld_log to its actual location (LOGFILE_$USERID) and checked these two are actually the same file. Maybe the log file permissions should be relaxed?

    -rw-r--r--    rimworld_log_1001
RimWorld 1.2.2900, HugsLib as per Steam, on Arch Linux.  
Possibly linked issues are: #73 (, #75 )  
Also thank you for all of your work in our community :o)

**Comment by UnlimitedHugs** [comment]
Hey, I appreciate the interest.
There were some outages for about a month due to authentication issues, but those should be resolved, at least on windows.
I have a fix for the Linux log path issue ready, just need to release it- hopefully in the nearest future. 
If we're lucky, it might solve this error, as well.

**Comment by tukoz** [comment]
Thanks UlimitedHugs! Note that the actual path to the log file on any Linux system could be noted as:

    /tmp/rimworld_log_$UID
Unless it's treated differently between Linux distros. Might be but I doubt it: Differentiating users files in `/tmp` is a security feature that's been implemented even on conservative distributions such as Debian for a while now.  
Path to the log is not the issue here since it's easy to fix oneself with a symlink. But for me the above issue has been unchanged since last February at least which is about 3 months. I believe that's more time than the authentication issues were around.

Thank you agian! You already made me a happy dude by just looking at this :)

**Comment by UnlimitedHugs** [comment]
True, the error type is different.
Looking at the code, the error can only be coming from from the Unity web request API. If the error pops up immediately (before a response is received), that might be due to a security issue- perhaps, your firewall or the kernel refusing the connection.
Say, could you post the stack trace logged by the publisher during this error? It should appear in the log console, which has a handy Copy button. Dev mode needs to be turned on in the Rimworld options.

**EDIT:** By the way! If you uncheck "Use recommended settings" in the publish confirm dialog, a "Copy to clipboard" button appears- useful in cases such as this.

**Comment by tukoz** [comment]
Of course; I should have shared the stack (?) log from start. Here's one from minutes ago:
```
[HugsLib][warn] Exception during log publishing (gist creation): System.Exception: Unknown Error
  at HugsLib.Utils.HugsLibUtility+<>c__DisplayClass22_0.<AwaitUnityWebResponse>b__0 () [0x000a6] in <e4b32d84f714481f906e5eea5e560e3b>:0 
Verse.Log:Warning(String, Boolean)
HugsLib.Utils.ModLogger:Warning(String, Object[])
HugsLib.Logs.LogPublisher:<BeginUpload>b__30_0(Exception)
HugsLib.Utils.<>c__DisplayClass22_0:<AwaitUnityWebResponse>b__0()
HugsLib.Utils.DoLaterScheduler:InvokeCallbacks(Queue`1)
HugsLib.Utils.DoLaterScheduler:OnUpdate()
HugsLib.HugsLibController:OnUpdate()
HugsLib.Patches.Root_Patch:UpdateHook()
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Play:Update()
```
>If you uncheck "Use recommended settings" in the publish confirm dialog, a "Copy to clipboard" button appears

Hadn't realized one can do that. Thanks a lot UnlimitedHugs :)

**Comment by tukoz** [comment]
Here is another yellow log that your last comment here made me think about. This one is from weeks ago but I've seen it a lot during the last couple months:

    Curl error 77: Error reading ca cert file from /etc/ssl/certs/ca-certificates.crt    
    (Filename: ./Modules/UnityWebRequest/Implementations/TransportCurl.cpp Line: 799)

'ca-certificates.crt' **is** present here; it's a symlink to a file that's *readable* for everyone.
