### ISSUE TITLE
Hugs, are you taking donations? Where can we drop you $ or help? 

### ISSUE THREAD

**Issue by j0nathontayl0r** [UnlimitedHugs/RimworldHugsLib#89]
I understand it might be more difficult because well, *broadly gestures to everything*, but maybe you have a crypto wallet I can drop funds to or similar for the work you do on HugsLib on RimWorld? Let us know, cheers. <3

**Comment by UnlimitedHugs** [comment]
Hey, thank you so much for your interest. I'm actually doing quite well on $- I currently do Unity development at a big multinational. Also, I was able to get out of Russia before the... *recent events*, so I'm doing great, all things considered.

Still, if you would like to send me something, the preferred way is through Litecoin: LeKrFDDLzVTdeg7fen9MVf6wG658uJspsD
And if you like, drop me a message on Discord so that I can thank you personally.

Finally, to anyone reading this, I appreciate you and thanks for using the mod. I never planned for it to be this popular, but I hope to keep up with the important updates, even as I work on other things.
